# Data Analysis

### SEN9120: Advanced Agent Based Modeling
Cruz Torres Francesco, 4999959
<br> Herzog Rico, 5095530

In [1]:
# Import necessary scintific computing, data analysis and visualization packages
%matplotlib inline
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt
import plotly.express as px
from mpl_toolkits.mplot3d import Axes3D
plt.style.use('ggplot')
import seaborn as sns


import scipy.stats as stats
import statistics
import math

In [2]:
for name in os.listdir("./results"):
    print(name)

outcomes2021-2-6-20-18.csv
outcomes2021-2-6-21-00.csv
outcomes2021-2-7-0-32_50 samples.csv
parameters2021-2-6-20-18.csv
parameters2021-2-6-21-00.csv
parameters2021-2-7-0-32_50 samples.csv

In [94]:
#access all results files and store them in dataframes

count_outcomes = 1
count_parameters = 1

for name in os.listdir("./results"):
    path = os.path.join("./results", name)
        
    if "outcomes" in name:
        globals()["outcomes_"+str(count_outcomes)] = pd.read_csv(path)
        count_outcomes += 1
        
    #othwerwise the filename starts with "parameters"
    else:
        globals()["parameters_"+str(count_parameters)] = pd.read_csv(path)
        count_parameters += 1

In [95]:
# for each couple of files (parameters ; outcome) merge the two files together
for i,j in zip(range(1,count_parameters), range(1,count_outcomes)):
    globals()["results_"+str(i)] = pd.merge(globals()["parameters_"+str(i)], globals()["outcomes_"+str(i)], left_on= "Unnamed: 0", right_on= "Run").drop("Unnamed: 0", axis=1)

In [99]:
# adjust the "Run" column such that each run is unique across all results files
results_2["Run"] = results_2["Run"] + results_1["Run"].iloc[-1] + 1
results_3["Run"] = results_3["Run"] + results_2["Run"].iloc[-1] + 1
results_3["Run"]

0       20
1       20
2       20
3       20
4       20
        ..
4995    69
4996    69
4997    69
4998    69
4999    69
Name: Run, Length: 5000, dtype: int64

In [102]:
# combine all results dataframes into one dataframe, where Run is the unique key column
results = pd.concat([results_1, results_2, results_3], axis = 0, )
results

,administrative-network-meetings,total-project-proposal-frequency,informal-meetings-frequency,green-energy-openness-change,political-variety-change,max-project-capacity,random-intial-trust,Run,Random Seed,MW_implemented_wind,MW_implemented_solar,MW_implemented_urban
0,8.0,8.0,15.0,1.0,4.0,1.0,True,0,0,40.0,325.0,166.5
1,8.0,8.0,15.0,1.0,4.0,1.0,True,0,1,60.0,179.0,159.0
2,8.0,8.0,15.0,1.0,4.0,1.0,True,0,2,64.0,90.0,145.5
3,8.0,8.0,15.0,1.0,4.0,1.0,True,0,3,48.0,178.0,147.0
4,8.0,8.0,15.0,1.0,4.0,1.0,True,0,4,50.0,385.0,172.5
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2.0,10.0,5.0,-3.0,-0.0,5.0,True,69,95,80.0,297.0,168.0
4996,2.0,10.0,5.0,-3.0,-0.0,5.0,True,69,96,68.0,209.0,180.0
4997,2.0,10.0,5.0,-3.0,-0.0,5.0,True,69,97,35.0,135.0,147.0
4998,2.0,10.0,5.0,-3.0,-0.0,5.0,True,69,98,65.0,225.0,154.5
4999,2.0,10.0,5.0,-3.0,-0.0,5.0,True,69,99,65.0,283.0,184.5